"""
PROJECT EULER - PROBLEM 2
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""
import sys
import math
def main():
    print 'Problem 2 - Project Euler'
    number = 0
    sumNumbers = 0
    fib =0
    while fib <= 4000000:
        fib = fibNums(number)
        if fib % 2 == 0:
            sumNumbers += fib
        number +=1
    print 'The sum is ' + str(sumNumbers)
def fibNums(n):
    a,b = 1,2
    for i in range(n-1):
        a,b = b,a+b
    return a
if __name__ == '__main__':
    main()
